permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: smalinuxer
  email: smalinuxer@gmail.com
  link: http://smalinuxer.github.io
  github: http://github.com/smalinuxer

# 站点信息
title: 202室
description: smalinuxer的202室
url: http://smalinuxer.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7xkw0v.com1.z0.glb.clouddn.com/shenle.jpeg
favicon: http://7xkw0v.com1.z0.glb.clouddn.com/shenle.jpeg

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
#disqus:
#  shortname: suyan-zh